# Generated by Django 4.0 on 2021-12-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211207_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='basket_id',
            field=models.IntegerField(default=5000000000000, primary_key=True, serialize=False, verbose_name='Basket id'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(default=2000000000000, primary_key=True, serialize=False, verbose_name='Customer id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=4000000000000, primary_key=True, serialize=False, verbose_name='Order id'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(default=7000000000000, primary_key=True, serialize=False, verbose_name='Product id'),
        ),
        migrations.AlterField(
            model_name='productbasketcard',
            name='product_basket_card_id',
            field=models.IntegerField(default=6000000000000, primary_key=True, serialize=False, verbose_name='Product basket card id'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_id',
            field=models.IntegerField(default=8000000000000, primary_key=True, serialize=False, verbose_name='Category id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(default=1000000000000, primary_key=True, serialize=False, verbose_name='User id'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist_id',
            field=models.IntegerField(default=3000000000000, primary_key=True, serialize=False, verbose_name='Wishlist id'),
        ),
    ]
