# Generated by Django 4.0 on 2021-12-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_basket_basket_id_alter_customer_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='basket_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Basket id'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Customer id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Order id'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Product id'),
        ),
        migrations.AlterField(
            model_name='productbasketcard',
            name='product_basket_card_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Product basket card id'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Category id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.BooleanField(verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='User id'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Wishlist id'),
        ),
    ]
