# Generated by Django 4.0 on 2021-12-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_basket_basket_id_alter_customer_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, verbose_name='Email'),
        ),
    ]
