# Generated by Django 4.0 on 2021-12-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='Please, enter your name.', max_length=255, verbose_name='Name'),
        ),
    ]
